package command;

public enum CommandName {

    GO_TO_ERROR_PAGE_COMMAND,
    GO_TO_PERSONAL_PAGE_COMMAND,
    GO_TO_ACCOUNTS_COMMAND,
    GO_TO_ACCOUNT_COMMAND,
    GO_TO_ACCOUNT_HISTORY_COMMAND,
    GO_TO_ADD_CARD_COMMAND,
    GO_TO_CARDS_COMMAND,
    GO_TO_CARD_COMMAND,
    GO_TO_CARD_HISTORY_COMMAND,
    GO_TO_SIGN_IN_COMMAND,
    GO_TO_SIGN_UP_COMMAND,
    GO_TO_PERSONAL_EDIT_COMMAND,
    SIGN_IN_COMMAND,
    LOG_OUT_COMMAND,
    PERSONAL_EDIT_COMMAND,
    ADD_CARD_COMMAND,
    DELETE_CARD_COMMAND,
    DELETE_ACCOUNT_COMMAND


}
