package command;

public enum CommandName {

    GO_TO_ERROR_PAGE_COMMAND,
    GO_TO_PERSONAL_PAGE_COMMAND,
    GO_TO_PAYMENTS_COMMAND,
    GO_TO_SIGN_IN_COMMAND,
    GO_TO_SIGN_UP_COMMAND,
    GO_TO_PERSONAL_EDIT_COMMAND,
    SIGN_IN_COMMAND,
    LOG_OUT_COMMAND,
    PERSONAL_EDIT_COMMAND,

}
